### ISSUE TITLE
key should be base32

### ISSUE THREAD

**Issue by ShankzPatil** [stefansundin/2fa-qr#1]
hi,

as checked you have consume direct string as base32. please try string containing 1, 8, 9, 0 then it will raise issue in authenticator.

otpauth://totp/Shashank?secret=IAmShashank11111111

solution: convert your secret to base32.
string: IAmShashank11111111
base32: JFAW2U3IMFZWQYLONMYTCMJRGEYTCMI

for your ref 
https://emn178.github.io/online-tools/base32_encode.html

then 
otpauth://totp/Shashank?secret=JFAW2U3IMFZWQYLONMYTCMJRGEYTCMI

best of luck...

**Comment by ShankzPatil** [comment]
Basically you can enter only base 32 char in secret.
Set is abcdefghijklmnopqrstuvwxyz234567
So whenver user enters char other than this issue arise.

**Comment by stefansundin** [comment]
Every website that I've encountered already gives you the secret in the correct format. If I encode it again then the QR code will not work.

I could add validation to the field to mark the string as invalid if it contains non-base32 characters.

**Comment by ShankzPatil** [comment]
ok

**Comment by ekkis** [comment]
I have a secret: `VJ53WhkuEq3PQ1B1QUXZ` for which I want to get a QR code.  the page generates an image but when I try to scan it with Google Authenticator I get the message: "The barcode '...' is not a valide authentication token barcode".  I tried converting the value to Base32: `IM4WWYLEKF3TE5JRKF4XQYZTJ5DVCYKVBI======` and also tried a hexdump: `43396b6164517732753151797863334f475161550a` but nothing seems to work.  what am I doing wrong?

**Comment by stefansundin** [comment]
@ekkis It doesn't look like a valid secret to me. Perhaps it is for some proprietary authenticator? Do you know what website generated it?

**Comment by ekkis** [comment]
ah.  you've solved my problem.  you're right.  that value was a random string used as a temporary token.  when I enter the actual secret your site works just fine.  a million thanks.
